# Generated by Django 3.2.8 on 2021-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://www.pngkey.com/detail/u2w7r5r5a9q8y3i1_best-classified-apps-default-user-profile/', null=True, upload_to='profile_pics/%Y/%m/%d'),
        ),
    ]
