# Generated by Django 3.2.8 on 2021-11-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='profile_pics/%Y/%m/%d'),
        ),
    ]
