# Generated by Django 3.2.8 on 2021-10-31 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211031_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userfollower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='userfollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
