# Generated by Django 3.2.8 on 2021-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211031_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='media/profile_pics/%Y/%m/%d'),
        ),
    ]
