# Generated by Django 3.2.8 on 2021-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.FileField(upload_to='feed_posts/%Y/%m/%d'),
        ),
    ]
