# Generated by Django 3.2.8 on 2021-11-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
